server:
    port: ${server.port:9092}

eureka:
    client:
        service-url:
            defaultZone: ${eureka.client.service-url.defaultZone}

spring:
    application:
        name: ${spring.application.name}
    datasource:
        url: ${spring.datasource.url}
        password: ${spring.datasource.password}
        username: ${spring.datasource.username}
        driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
